set -g default-terminal "screen-256color"

unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf

set -g allow-rename off
set -g automatic-rename off

# pane resize bindings (option+)
bind -n M-k resize-pane -U 1
bind -n M-j resize-pane -D 1
bind -n M-h resize-pane -L 1
bind -n M-l resize-pane -R 1

set -g mouse on

set -g @plugin 'tmux-plugins/tpm'

# list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator'

# catppuccin
set -g @catppuccin-flavour 'mocha'
set -g status-position top

set -g @catppuccin_window_status_style "rounded"

# force tmux window names for all states
set -g @catppuccin_window_text "#I #W"
set -g @catppuccin_window_default_text "#I #W"
set -g @catppuccin_window_current_text "#I #W"

# Load catppuccin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_date_time}"
set -agF status-right "#{E:@catppuccin_status_battery}"

set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cpu'

# which-key setup
set -g @plugin 'alexwforsythe/tmux-which-key'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

